### ISSUE TITLE
Detection seems to fail when AdBlock is initially paused an then un-paused after page load

### ISSUE THREAD

**Issue by jpfranco** [sitexw/FuckAdBlock#18]
Hey guys, so I'm testing this on Chrome with the standard AdBlock extension from https://getadblock.com/. Using your test page, if I pause the ad blocker before loading the page and then un-pause it after loading has finished, clicking on the "Check Again" button tells me that AdBlock is not enabled.

Is this a known issue or is it something new? Thanks

**Comment by sitexw** [comment]
Indeed, I managed to do the same again.
But one can not say that this is a bug or dysfunction because AdBlock really reactivates at page reload.
You can try this on other site with the pub (the true) and you will see that advertising is still displayed, so this proves that AdBlock is not yet activated.

Well, nothing serious.

**Comment by jpfranco** [comment]
Yes it seems that AdBlock is unable to detect ad elements on the DOM after it's un-paused, however, it looks like it's still able to block http requests to ad servers (such as VAST requests for video ads). In the specific case of video ads, this means that a user could circumvent an AdBlock restriction by loading the page with AdBlock paused, and then un-pausing it afterwards in order to disable mid-roll ads (or any ad-related tracking), for example. This same behavior is also present with AdBlock Plus.

Anyway, I'm not sure whether this falls within the scope of your library, but it seems like an extra http check would be necessary in order to prevent this loophole.

**Comment by sitexw** [comment]
Ok, I see. This requires nevertheless a lot of manipulation of the user.
Anyway, I'll watch it and see what I can do. Because the main problem is the creation of http request that consumes bandwidth and client resources.

In short, I look at that and I'll let you know.
I'd probably do a "beta" branch, and we will test this together.

**Comment by sitexw** [comment]
Here is a small example: https://jsfiddle.net/sitexw/m8puceja/
Called me if you find it correct.

**Comment by sitexw** [comment]
Check V4 (# 34)
