### ISSUE TITLE
It works

### ISSUE THREAD

**Issue by justjanne** [sitexw/FuckAdBlock#26]
The script works, this is a major moral issue – if the user uses AdBlock to block unwanted content from running on their system, it is not morally acceptable to force them to accept content (like it’s being done here)

This is a moral and philosophical issue, not a technical one.

**Comment by lexoyo** [comment]
:rowboat:

**Comment by timk95** [comment]
Why assume that you would use this to block users using an AdBlocker? You could also use it to inform people that your website is losing income because of AdBlockers.

90% of the people installing AdBlockers do it because some website drown you with ads. If you use this script to inform people that your losing income to keep the site online allot of them will accept a exception in the block list.

So, nothing morally wrong with this script.

**Comment by lexoyo** [comment]
:+1:

**Comment by sitexw** [comment]
:+1:

**Comment by justjanne** [comment]
By the way, here is a solution to the issue:

```javascript
// ==UserScript==
// @name        fuck-fuckadblock
// @namespace   de.kuschku.ffab
// @version     1
// @grant       none
// ==/UserScript==

var eventCallback = function () {
  if (window.fuckAdBlock) window.fuckAdBlock._options.baitClass = "kjdftriuhdiuhiuohiuehue";
}

if(window.addEventListener !== undefined) {
  window.addEventListener('load', eventCallback, false);
} else {
  window.attachEvent('onload', eventCallback);
}

**Comment by justjanne** [comment]
I wrote this solution because several websites started not showing any content at all anymore if one disabled the ads.
