### ISSUE TITLE
Doesn't work with IOS 9 Adblocking

### ISSUE THREAD

**Issue by systemaddict** [sitexw/FuckAdBlock#28]
Hi

I've tested this against the IOS 9 beta and I don't think it works.

I used this Adblocking-extension:

https://github.com/krishkumar/BlockParty

**Comment by sitexw** [comment]
Thanks for your feedback.

I think this is normal, because "BlockParty" blocks only file calls (advertising JS, ...).
Can be seen in blocking JSON: https://github.com/krishkumar/BlockParty/blob/d15127191cb966e3723c110d5ba04bf91c181000/RediffBlock/blockerList.json
I think we will have to implement the HTTP request detection system presented here: #18
