### ISSUE TITLE
Detecting Adblock when there adblock is disabled?

### ISSUE THREAD

**Issue by deivid725** [sitexw/FuckAdBlock#59]
https://kyogo.me/adblock 

I copy and pasted the code. I don't know why it keeps saying adblock is detected when it is not.

**Comment by sitexw** [comment]
For me, it works. You use what exactly blocker?

**Comment by pyper** [comment]
I have seen something similar before.  What happens is some CSS framework, or JS Framework, graphic change to make the page load pretty, etc.  Sets the body elements to display none or visibility hidden for a fraction of a second, thus causing a false positive.  It then removes the CSS as the page continues to load.  The funny thing it is more pronounced when the browser is fast.  For example, Safari is very fast and may get the problem there, but not in FF or Chrome.  Anyhow do this to test it:

1) Open up a console.  It slows down the page load enough that you can verify it is a problem caused by a temporary CSS state.

2) Put in a event to test for a false positive as soon as you can.  So first chance you can manipulate the DOM grab any child of body and see if it has display none or visibility hidden and output a alert or console.log indicating so.  It will likely catch it fast enough to tell you that was the issue.

**Comment by deivid725** [comment]
So I think it is beta v4 that is not working! 
I use the regular adblock.  https://getadblock.com/ 

Beta v4:
https://kyogo.me/adblockv4

Original:
https://kyogo.me/adblock

**Comment by sitexw** [comment]
In this case, I think this is normal because the file "fuckadblock.min.js" does not exist :
![image](https://cloud.githubusercontent.com/assets/2950561/18888170/83d177ba-84f7-11e6-83c2-3c4f70c22e98.png)

**Comment by deivid725** [comment]
Fixed it. Now I will try to work out the integrity for maximum secrurity

**Comment by sitexw** [comment]
Great ! Yes, I advise you very strongly integrity system, it can secure better detection.

**Comment by deivid725** [comment]
Do I need to change the SHA code for my website or do I keep it the same?

**Comment by sitexw** [comment]
As long as the file does not change a character, you have to keep the same SHA. The server name or other web site, has no impact on the SHA.
But if by chance, you want to compress the file (mimify) that would remake the SHA on this site : https://www.srihash.org/

**Comment by deivid725** [comment]
Got this error with the maximum security.

<img width="1399" alt="screen shot 2016-09-27 at 2 38 18 pm" src="https://cloud.githubusercontent.com/assets/20713570/18888934/24373916-84c0-11e6-8d11-9cd2066809b4.png">

**Comment by sitexw** [comment]
This one works for me (for fuckadblock.min.js) :
```integrity="sha384-oiO90JrGr6v49XI21iWwrxl1QY51C48/8D/qofKneFlKcV64YuSuug2GdqrdefBo"```

**Comment by deivid725** [comment]
You are awesome! It works ! Thanks so much 👍
