### ISSUE TITLE
DELETE THIS BAD SCRIPT! IS NOT GOOD

### ISSUE THREAD

**Issue by ghost** [sitexw/FuckAdBlock#81]
WHY YOU GUYS ARE CODING THOSE TO BLOCK PEOPLE FROM BLOCKING ADS!? ANYWAY I BYPASSED IT, BUT I SWEAR, I HATE YOU GUYS WHEN YOU CODE THIS STUPID STUFF FOR RESTRICTING PEOPLE TO USE INTERNET WITHOUT ADS -.-

**Comment by shoestar** [comment]
I do not know if you work for free but most people don't because they need money to pay the bills. This is why the web is not free and there are various models to earn money e.g. displaying ads. The best thing I can advise to you is stop using websites that depend on ads.

You could start by reading the ad-free donation based article https://en.m.wikipedia.org/wiki/All_caps

**Comment by PieGuy7896** [comment]
retard @marcocorriero

**Comment by ghost** [comment]
@PieGuy7896 You aren't huh? GTFO

**Comment by PieGuy7896** [comment]
@marcocorriero atleast I don't sit in a wheelchair and pretend to be 18 years old with a bowl cut.

**Comment by ghost** [comment]
Gtfo mate

________________________________

**Comment by PieGuy7896** [comment]
@marcocorriero raged irl

**Comment by typhlosion147** [comment]
@marcocorriero Could you speak a little louder? I couldn't hear you!

**Comment by aveao** [comment]
mfw @typhlosion147 defends a capitalist BS software

**Comment by sparskakyl** [comment]
@marcocorriero Yells at FuckAdBlock Developer (2018, colorized)

**Comment by typhlosion147** [comment]
@aveao Not really defending it lul, @marcocorriero is just a moron for trying to make people change stuff like this

**Comment by aveao** [comment]
@typhlosion147 doesn't require you to explicitly state your hate

whatever

shrugz

**Comment by vbh689** [comment]
OMEGALUL

**Comment by PieGuy7896** [comment]
@typhlosion147 @marcocorriero is a downy anyway just ignore him he can't help that he has an extra chromosome man!

**Comment by aveao** [comment]
I'm not familiar with the person or anything, but I still have a couple words.

If they're indeed diagnosed with Down Syndrome, calling them offensive terms such as "downy", "retard" or "moron" will not help. Ignoring them is not a good option, but if all you'll do is calling them a "downy" or "retard", perhaps you should listen to your own advice and ignore the existance of this person and this issue. Furthermore, using such hateful terms will just escalate the issue at hand and reduce people's views about how inclusive, professional and respectful the Open Source community is.

Everyone can raise concerns about anything, and @marcocorriero chose to raise an ethical concern about this software (which is a concern that I persomally agree with, but I'm keeping this comment objective). There's nothing wrong with wanting change, even if the change probably won't happen.

blegh.

**Comment by ghost** [comment]
Nah, ignore the kids @ave, they are just trolls

________________________________

**Comment by waqarkhan3389** [comment]
I don't mind ads, its only when they are intrusive I have a problem. 
Some websites you go to will pop-up everywhere with ads, 100s of new pages per click. Whereas if you read a newspaper online, and there are some ads on the side, then this is totally fair.

As someone already pointed out, websites need to make money to pay for their costs etc one way or another. They can either charge you a subscription (Netflix, Youtube Premium etc) or they display ads, like many other sites.

So I think its totally wrong to say that people should browse their favourite sites with ad blocker because those sites rely on your traffic to stay alive! I have a whitelist of sites I allow to show ads, forexample, I read this newspaper https://www.theguardian.com/uk - they show ads and provide a service for me. 

So a middle ground is needed, not calling people "retard" and things like that or saying "DELETE SCRIPT BLA BLA BLA". 

The author is perfectly entitled to his/her view on ads and this is an open source community where people can code freely. If you don't agree with it move along, Im only commenting because someone called them a "retard" and the OP was in an authoritative tone, trying to force the author to take down the code.

**Comment by i1u5** [comment]
Ads aren't the problem, pop-ups and forced ads are.
That's why I use Adblock, I still allow non-harmful ads AND YOU SHOULD TOO.

**Comment by aveao** [comment]
you can't tell me what to do

**Comment by PieGuy7896** [comment]
@waqark3389 @aveao problem is @marcocorriero steals others code without crediting the original author - thats why I've called him over.

**Comment by ghost** [comment]
I dont steal codes you dumbass


________________________________
Da: Brandon <notifications@github.com>
Inviato: giovedì, luglio 19, 2018 10:45 AM
A: sitexw/FuckAdBlock
Cc: marcocorriero; Mention
Oggetto: Re: [sitexw/FuckAdBlock] DELETE THIS BAD SCRIPT! IS NOT GOOD (#81)


@waqark3389<https://github.com/waqark3389> @aveao<https://github.com/aveao> problem is @marcocorriero<https://github.com/marcocorriero> steals others code without crediting the original author - thats why I've called him over.

**Comment by i1u5** [comment]
"you can't tell me what to do" just kys already, guys you're making all this shitty nonsense argument over an abandoned script, grow up already.

**Comment by FUCKFUCKADBLOCK** [comment]
SUPPORT YOU

**Comment by Telesphoreo** [comment]
don't worry marco makes good codes he's very qualified to speak on this issue we should all listen to him the world revolves around him and his amazing cosmetic changes that he can make!!! marco makes some of the best codes around in town he's the best coder in the world!!! **LOVE** the cosmetic changes!! amirite

**Comment by PieGuy7896** [comment]
- slaps @marcocorriero on head -
"this beast can make the goodest codes"

**Comment by PieGuy7896** [comment]
can you not beaner

**Comment by wannesdebacker** [comment]
You do know it's illegal (at least in the civilized world, don't know in America) to detect ad-block-scripts right? So i hope you guys get sued.

And this point:

>  do not know if you work for free but most people don't because they need money to pay the bills. This is why the web is not free and there are various models to earn money e.g. displaying ads. The best thing I can advise to you is stop using websites that depend on ads.

Is not a really point, ads are just terrible, slow, using data (that should be illegal). I don't care that websites don't make money elseway, then find another way, this is not the way to go.

**Comment by shoestar** [comment]
I couldn't find a resource that says that detecting ad block scripts is basically illegal. I guess you live in the EU and refer to https://twitter.com/alexanderhanff/status/722861362607747072 which in my opinion only says that some things have to be declared in order to use them. Which I think is completely fair.

I fully agree with you that the current privacy and data protection guidelines must also be observed by advertisers. Nevertheless, advertising is an important element to offer services on the Internet without charging money. In my opinion, it is dishonest to use services without using monetization services and this can be compared to theft.

**Comment by yell0wsuit** [comment]
Too late for this.
Blocking adblockers isn't illegal, but ads with malicious code and tracking should be banned, and I'm going to continue blocking those ads (even with this script). No matter how aggressive FuckAdBlock is, whenever those ads appear, I'll try to block this script.

**Comment by pharrowboy** [comment]
What if I told you, this script could become unnecessary. In a world where browsers promote webgl, one man used webgl to launch popup ads that are UNBLOCKABLE because they are user initiated without the users knowledge. 


Sounds like a movie doesn't it? But I figured out How to do it, you can too.

**Comment by JobcenterTycoon** [comment]
> 
> 
> What if I told you, this script could become unnecessary. In a world where browsers promote webgl, one man used webgl to launch popup ads that are UNBLOCKABLE because they are user initiated without the users knowledge.
> 
> Sounds like a movie doesn't it? But I figured out How to do it, you can too.

uBlock Origin can block this

**Comment by pharrowboy** [comment]
as far as im aware the only way to block webgl, is via disabling it in your browser. ublock origin can block WEBRTC. but WEBGL is created in unity3d, its the same thing 3d web browser games are made  from.

i attempted to use ublock origin in my intial tests to try and block the custom webgl ad code. it only blocked the element from showing, but the webgl still loaded in the background of the browser. and so did my code.

im not planning to release the code, so you dont have to worry. i figured since the page i got the webgl popup code that i modified and used in a custom unity3d game,  was deleted by the owner. i'd say the code would be too dangerous in the wild.

**Comment by JobcenterTycoon** [comment]
omg

at least when uBlock Origin can’t block this but it need to be blocked uBlock Origin will get a update for this

**Comment by boxvers** [comment]
+

**Comment by boxvers** [comment]
If you found site when try you to disable adblock, just close this site and never visit again

**Comment by hktr92** [comment]
there is the other side of the coin.

I have a web app that injects multiple Vue components via HTML `<script>` tag and the request is blocked by ad block technology because some of my components has `tracker` in URL. I did a workaround for plugins, but against Brave is ineffective. and before throwing with rocks: yes, it's bad product design, but we're in the middle of UI refactoring on a production-ready code that runs well for almost 3 years.

This is why I am going to implement this library and give a huge thank you: to display a simple notice to our  users that they are using plugins that might break user experience and to whitelist our web app.

It's behind a paywall anyway, so no ad revenue on that website, meaning no need for using adblock on our app (except for google analytics, which doesn't really work either). to be fair, our company never used ad services to gain revenue for our products because of this, due to our business niche.

**Comment by aveao** [comment]
Can y'all please stop bumping this issue? You're not going to get anywhere.
